# Generated by Django 4.2.9 on 2026-02-27 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("election", "Election"),
                            ("contest", "Talent / Awards Contest"),
                            ("survey", "Survey"),
                            ("live_show", "Live Show / Awards"),
                        ],
                        default="election",
                        max_length=20,
                    ),
                ),
                (
                    "voting_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Single Choice"),
                            ("multiple_choice", "Multiple Choice"),
                            ("ranked_choice", "Ranked Choice"),
                            ("yes_no", "Yes / No"),
                            ("poll", "Poll / Survey"),
                        ],
                        default="single_choice",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("allow_multiple_votes", models.BooleanField(default=False)),
                ("max_votes_per_user", models.IntegerField(default=1)),
                ("max_choices_per_vote", models.IntegerField(default=1)),
                ("require_auth", models.BooleanField(default=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_banners/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="event_thumbs/"),
                ),
                ("theme_color", models.CharField(default="#6366f1", max_length=20)),
                ("theme_config", models.JSONField(blank=True, default=dict)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "price_per_vote",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("currency", models.CharField(default="GHS", max_length=5)),
                ("show_live_results", models.BooleanField(default=True)),
                ("results_visible", models.BooleanField(default=False)),
                ("languages", models.JSONField(default=list)),
                ("total_votes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "voting_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single_choice", "Single Choice"),
                            ("multiple_choice", "Multiple Choice"),
                            ("ranked_choice", "Ranked Choice"),
                            ("yes_no", "Yes / No"),
                            ("poll", "Poll / Survey"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="candidates/"),
                ),
                ("video_url", models.URLField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("vote_count", models.IntegerField(default=0)),
                ("vote_percentage", models.FloatField(default=0.0)),
                ("extra_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="events.category",
                    ),
                ),
            ],
            options={
                "db_table": "candidates",
                "ordering": ["order", "name"],
            },
        ),
    ]
