# Generated by Django 4.2.9 on 2026-06-12 19:32

import cloudinary_storage.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_candidate_unique_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated 6-char unique vote code e.g. AB3X9K",
                max_length=6,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="candidates/",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="event_banners/",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("election", "Election"),
                    ("organizational", "Organizational Election"),
                    ("contest", "Talent / Awards Contest"),
                    ("survey", "Survey"),
                    ("live_show", "Live Show / Awards"),
                ],
                default="election",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="event_thumbs/",
            ),
        ),
        migrations.AlterField(
            model_name="votergroup",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="voterroll",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
