# Generated by Django 5.2 on 2026-08-18 23:35

import cloudinary_storage.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_candidate_code_alter_candidate_photo_and_more"),
        ("officials", "0002_withdrawalrequest_payment_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Legal/full name — internal use only.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Contact number — used for SMS notifications.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="nominations_open",
            field=models.BooleanField(
                default=True,
                help_text="Whether this event currently accepts public self-nominations.",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated 4-char unique contestant code e.g. AB3X",
                max_length=6,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(
                help_text="Stage name — shown publicly on the ballot.", max_length=200
            ),
        ),
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("stage_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=30)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="nominations/",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Optional — reason for nomination."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set automatically once approved.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nomination",
                        to="events.candidate",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="events.category",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="events.event",
                    ),
                ),
                (
                    "reviewed_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_nominations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by_official",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_nominations",
                        to="officials.official",
                    ),
                ),
            ],
            options={
                "db_table": "nominations",
                "ordering": ["-created_at"],
            },
        ),
    ]
