# Generated by Django 4.2.9 on 2026-02-27 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "voter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("voter_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("voter_name", models.CharField(blank=True, max_length=150, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_fingerprint", models.CharField(blank=True, max_length=200)),
                ("votes_cast", models.IntegerField(default=0)),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_flagged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_sessions",
                        to="events.event",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vote_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vote_sessions",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("encrypted_data", models.TextField()),
                ("payment_ref", models.CharField(blank=True, max_length=100)),
                ("is_paid", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="events.candidate",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="events.category",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="events.event",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="voting.votesession",
                    ),
                ),
            ],
            options={
                "db_table": "votes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FraudFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fraud_type",
                    models.CharField(
                        choices=[
                            ("duplicate_ip", "Duplicate IP"),
                            ("duplicate_device", "Duplicate Device"),
                            ("rapid_voting", "Rapid Voting"),
                            ("payment_anomaly", "Payment Anomaly"),
                            ("manual", "Manually Flagged"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cleared", "Cleared"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_flags",
                        to="events.event",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_flags",
                        to="voting.votesession",
                    ),
                ),
            ],
            options={
                "db_table": "fraud_flags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="votesession",
            index=models.Index(
                fields=["event", "voter"], name="vote_sessio_event_i_6b57ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="votesession",
            index=models.Index(
                fields=["voter_email"], name="vote_sessio_voter_e_17b852_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="votesession",
            index=models.Index(
                fields=["ip_address"], name="vote_sessio_ip_addr_b2162b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["event", "category"], name="votes_event_i_b1bb40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["candidate"], name="votes_candida_da1a33_idx"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["session"], name="votes_session_78ff46_idx"),
        ),
    ]
