# Generated by Django 4.2.9 on 2026-03-16 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_hide_vote_counts_event_results_published"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoterGeoLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("country", models.CharField(blank=True, max_length=100)),
                ("country_code", models.CharField(blank=True, max_length=5)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_logs",
                        to="voting.votesession",
                    ),
                ),
            ],
            options={
                "db_table": "voter_geo_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("vote_reset", "Vote Reset"),
                            ("manual_recovery", "Manual Vote Recovery"),
                            ("fraud_resolved", "Fraud Flag Resolved"),
                            ("status_changed", "Event Status Changed"),
                            ("results_published", "Results Published"),
                            ("session_suspended", "Session Suspended"),
                            ("candidate_added", "Candidate Added"),
                            ("candidate_removed", "Candidate Removed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "admin_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
