# Generated by Django 4.2.9 on 2026-03-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="candidate_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="category_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
